spring:
  banner:
    image:
      location: classpath:banner.txt
  datasource:
    url: jdbc:mysql://144.34.240.197:9062/ms_zhou?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null

# MyBatis Plus 的配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: AUTO # 自增 ID
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: si.qi.clazz.entity

server:
  port: 8080
  servlet:
    context-path: /zhou-class